-- config/autocmds.lua - event hooks, loaded by LazyVim after its own.
-- LazyVim's defaults already cover the usual ones (highlight on yank,
-- restore cursor position, auto-create missing parent dirs on save, strip
-- trailing whitespace notifications, close scratch buffers with q).
-- See: https://lazyvim.org/configuration/general
--
-- Add hooks here rather than in a plugin file, e.g.:
--
--   vim.api.nvim_create_autocmd("FileType", {
--     pattern = { "gitcommit", "markdown" },
--     callback = function() vim.opt_local.spell = true end,
--   })

-- The kitty in_editor user variable used to be set here, so kitty could
-- release ctrl+shift+arrow only while an editor had focus. It never took
-- effect over ssh -- the keys kept being swallowed -- so kitty.conf now
-- unmaps them outright and this emission was removed rather than left as
-- dead code that looks load-bearing. See the comment in kitty.conf.
